[book]
authors = ["Vector AI Engineering <ai_engineering@vectorinstitute.ai>"]
description = "A streamlined reference manual for AI practitioners, students, and developers to quickly look up core concepts and mock implementations"
language = "en"
multilingual = false
src = "src"
title = "AI Pocket Reference: High-Performance AI Computing"

[build]
build-dir = "../../pocket_references/compute"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds

# preprocessors
[preprocessor.github-authors]
command = "mdbook-github-authors"

[preprocessor.ai-pocket-reference]
command = "mdbook-ai-pocket-reference"
after = [ "github-authors" ]


# renderer options
[output.html]
mathjax-support = true
additional-css = ["../_common/mdbook-ai-pocket-reference.css"]
