name: 📝 Edit Request
description: Submit a request to edit a pocket reference
title: "[EDIT REQUEST]"
labels: ["edit"]
project: ["VectorInstitute/7"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Edit Request Template
        Please provide detailed information about the edit you'd like to make to an existing pocket reference.

  - type: input
    id: reference-name
    attributes:
      label: Pocket Reference Name
      description: Specify which pocket reference needs editing
      placeholder: e.g., JavaScript Reference, Python Cheat Sheet
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: Describe or quote the current content that needs modification
      placeholder: Provide the specific section or text that requires editing
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: Clearly explain the edits you are suggesting
      placeholder: Provide a detailed description of the changes, including any new text or corrections
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Edit
      description: Why are these changes necessary?
      placeholder: Explain the rationale behind the proposed edits
    validations:
      required: true

  - type: checkboxes
    id: edit-type
    attributes:
      label: Type of Edit
      description: Select the type of changes you're proposing
      options:
        - label: Correction of factual information
        - label: Clarification of existing content
        - label: Adding missing information
        - label: Updating outdated content
        - label: Improving readability
        - label: Other (please specify in the reason)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help in reviewing the edit request
      placeholder: Include screenshots, links, or any supplementary information
