name: 🆕 New Pocket Reference Request
description: Request a new pocket reference
title: "[NEW REQUEST] <insert-new-pocket-ref-name>"
labels:
  - new
projects: ["VectorInstitute/7"]

body:
  - type: markdown
    attributes:
      value: |
        ## New Pocket Reference Request Template
        Help us expand our collection of AI pocket references by suggesting a new one!

  - type: dropdown
    id: reference-book
    attributes:
      label: Book
      description: Select the book to which this Pocket Reference belongs
      options:
        - fundamentals
        - nlp
        - cv
        - rl
        - fl
        - responsible_ai
        - compute
    validations:
      required: true

  - type: input
    id: reference-title
    attributes:
      label: Pocket Reference Title
      description: What would you like the new pocket reference to cover?
      placeholder: e.g., attention.md, differential_privacy.md, backpropagation.md
    validations:
      required: true

  - type: textarea
    id: reference-content
    attributes:
      label: Proposed Content
      description: Describe the key concepts to be covered in this pocket reference
      placeholder: Outline the main topics, concepts, techniques, or models that should be included
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this pocket reference valuable?
      placeholder: Explain why this topic deserves a pocket reference and how it would benefit the AI community
    validations:
      required: true

  - type: checkboxes
    id: content-type
    attributes:
      label: Content Types
      description: Select the types of content that should be included
      options:
        - label: Theoretical foundations
        - label: Mathematical formulations
        - label: Code examples
        - label: Diagrams/visualizations
        - label: Practical applications
        - label: Common pitfalls/challenges
    validations:
      required: true

  - type: textarea
    id: useful-links
    attributes:
      label: Additional Resources
      description: |
        Provide supporting materials that could help in creating this pocket reference.
        This could include:
        - Academic papers
        - Official documentation
        - Tutorial links
        - Blog posts
        - Implementation examples
      placeholder: List any relevant resources with brief descriptions of their relevance
    validations:
      required: true
