name: 🆕 New Pocket Reference Request
description: Request a new pocket reference
title: "[NEW REQUEST] <insert-new-pocket-ref-name>"
labels:
  - new
projects: ["VectorInstitute/7"]

body:
  - type: markdown
    attributes:
      value: |
        ## New Pocket Reference Request Template
        Help us expand our collection of AI pocket references by suggesting a new one!

  - type: input
    id: reference-title
    attributes:
      label: Proposed AI Pocket Reference
      description: What would you like the new pocket reference to cover?
      placeholder: e.g., Attention, Differential Privacy, Back Propagation
    validations:
      required: true

  - type: textarea
    id: reference-content
    attributes:
      label: Proposed Content
      description: Describe the content and focus of the proposed AI pocket reference
      placeholder: Provide details about the concepts, models, techniques, etc., to be covered
    validations:
      required: true

  - type: textarea
    id: useful-links
    attributes:
      label: References
      description: Provide links to resource materials on which the Pocket Reference should be based.
      placeholder: e.g., https://arxiv.org/pdf/1706.03762
    validations:
      required: true

  - type: dropdown
    id: reference-book
    attributes:
      label: Reference Area
      description: Select the area of AI to which this Pocket Reference belongs
      options:
        - AI Fundamentals
        - Natural Language Processing (NLP)
        - Computer Vision (CV)
        - Reinforcement Learning (RL)
        - Federated Learning (FL)
        - Responsible AI
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this pocket reference valuable?
      placeholder: Explain the need for this reference, its potential impact, or how it fills a gap in existing resources
    validations:
      required: true
