[book]
authors = ["Vector AI Engineering <ai_engineering@vectorinstitute.ai>"]
description = "A streamlined reference manual for AI practitioners, students, and developers to quickly look up core concepts and mock implementations"
language = "en"
multilingual = false
src = "src"
title = "AI Pocket Reference: Responsible AI"
editors = [
    "Veronica Chatrath <veronica.chatrath@vectorinstitute.ai>",
    "Shaina Raza <shaina.raza@vectorinstitute.ai>",
    "Masoumeh Shafieinejad <masoumeh@vectorinstitute.ai>",
    "David Emerson <david.emerson@vectorinstitute.ai>",
    "Andrei Fajardo <andrei.fajardo@vectorinstitute.ai>",
]

[build]
build-dir = "../../pocket_references/responsible_ai"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds

# preprocessors
[preprocessor.github-authors]
command = "mdbook-github-authors"

[preprocessor.ai-pocket-reference]
command = "mdbook-ai-pocket-reference"
after = [ "github-authors" ]


[output.html]
mathjax-support = true
additional-css = ["../_common/mdbook-ai-pocket-reference.css"]
git-repository-url = "https://github.com/VectorInstitute/ai-pocket-reference"
git-repository-icon = "fa-github"
