name: Publish

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pull-requests: write  # To create a PR from that branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install mdbook and preprocessors if needed  # Pin of mdbook should match the version used to generate theme.bbs template
        run: |
          (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "0.4.44" mdbook)
          (test -x $HOME/.cargo/bin/mdbook-ai-pocket-reference ||cargo install mdbook-ai-pocket-reference)
          (test -x $HOME/.cargo/bin/mdbook-github-authors || cargo install mdbook-github-authors)
          (test -x $HOME/.cargo/bin/cargo-update || cargo install cargo-update)
          cargo install-update mdbook-ai-pocket-reference mdbook-github-authors

      - name: Build books
        run: |
          mdbook build books/nlp
          mdbook build books/compute
          mdbook build books/responsible_ai
          # mdbook build books/fundamentals
          # mdbook build books/cv
          # mdbook build books/rl
          # mdbook build books/fl

      - name: Copy static assets to build folder
        run: |
          cp -r static/. pocket_references/

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: pocket_references # The folder the action should deploy.
