name: Publish

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pull-requests: write  # To create a PR from that branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install mdbook and preprocessors if needed  # Pin of mdbook should match the version used to generate theme.bbs template
        run: |
          (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "0.4.44" mdbook)
          (test -x $HOME/.cargo/bin/mdbook-ai-pocket-reference ||cargo install mdbook-ai-pocket-reference)
          (test -x $HOME/.cargo/bin/mdbook-github-authors || cargo install mdbook-github-authors)

      - name: Update preprocessors if necessary
        run: |
          LATEST_AIPR=$(cargo search mdbook-ai-pocket-reference | grep -o "mdbook-ai-pocket-reference = \"[0-9.]*\"" | cut -d'"' -f2)
          CURRENT_AIPR=$($HOME/.cargo/bin/mdbook-ai-pocket-reference --version | grep -o "[0-9.]*")
          if [ "$CURRENT_AIPR" != "$LATEST_AIPR" ]; then
            cargo install --force mdbook-ai-pocket-reference
          fi

          LATEST_GH=$(cargo search mdbook-github-authors | grep -o "mdbook-github-authors = \"[0-9.]*\"" | cut -d'"' -f2)
          CURRENT_GH=$($HOME/.cargo/bin/mdbook-github-authors --version | grep -o "[0-9.]*")
          if [ "$CURRENT_GH" != "$LATEST_GH" ]; then
            cargo install --force mdbook-github-authors
          fi

      - name: Build books
        run: |
          mdbook build books/compute
          mdbook build books/fl
          mdbook build books/nlp
          mdbook build books/responsible_ai
          # mdbook build books/fundamentals
          # mdbook build books/cv
          # mdbook build books/rl

      - name: Copy static assets to build folder
        run: |
          cp -r static/. pocket_references/

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: pocket_references # The folder the action should deploy.
